name: Processar Dados do Painel

on:
  workflow_dispatch: # Permite rodar manualmente
  schedule:
    - cron: '0 * * * *' # Roda a cada hora (ex: 13:00, 14:00, etc.)
  push:
    paths:
      - 'dados_brutos/**' # Roda sempre que um arquivo for alterado na pasta dados_brutos

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar script de processamento de dados
        run: python scripts/process_data.py

      - name: Fazer commit e push do data.json
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add docs/data.json
          # Apenas faz o commit se houver mudanças no arquivo
          git diff --staged --quiet || git commit -m "Atualiza data.json processado"
          git push